# Generated by Django 3.2.7 on 2021-09-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFIDFapp', '0002_idf_tf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf',
            name='doc_number',
            field=models.PositiveIntegerField(),
        ),
    ]
