# Generated by Django 3.2.7 on 2021-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFIDFapp', '0003_alter_tf_doc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idf',
            name='term',
            field=models.CharField(max_length=50),
        ),
    ]
