# Generated by Django 3.2.7 on 2021-09-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TFIDFapp', '0004_alter_idf_term'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tf',
            name='term',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='TFIDFapp.idf'),
        ),
    ]
