# Generated by Django 3.2.7 on 2021-09-06 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TFIDFapp', '0006_alter_tf_term'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idf',
            name='id',
        ),
        migrations.AlterField(
            model_name='idf',
            name='term',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
