# Generated by Django 3.1.3 on 2021-09-07 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TFIDFapp', '0008_auto_20210907_1756'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='AddFile',
        ),
    ]
